export interface TechnicalInsightsData {
    Id: string,
    Slug: string,
    Symbol: string,
    Exchange: string,
    Interval: string,
    CandleMetrics: object,
    AwesomeIndicator: object,
    WillyIndicator: object,
    MacdIndicator: object,
    MovingAveragesIndicator: object,
    RetracementsIndicator: object,
    RsiIndicator: object,
    ObvIndicator: object,
    BopIndicator: object,
    CciIndicator: object,
    CmfIndicator: object,
    ForceIndexIndicator: object,
    KeyReversalsIndicator: object,
    MarubozuIndicator: object,
    MfiIndicator: object,
    SqueezeIndicator: object,
    TrixIndicator: object,
    UltimateIndicator: object,
    TdSequentialIndicator: object,
    DateIngested: object
}
